name: Build RNX

on:
  workflow_call:
    inputs:
      vmImage:
        required: false
        default: 'windows-latest'
        type: string
      configuration:
        required: false
        default: 'Debug'
        type: string
      platform:
        required: false
        default: 'x64'
        type: string

jobs:
  package:
    name: Build RNX ${{ inputs.configuration }} ${{ inputs.platform }}
    runs-on: ${{ inputs.vmImage }}
    steps:
    - uses: actions/checkout@v4

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2

    - name: yarn install
      run: yarn install 

    - name: build TS
      run: yarn build

    - name: build ReactNativeXaml.sln
      run: msbuild /restore /p:RestoreLockedMode=true /p:RestorePackagesConfig=true package\windows\ReactNativeXaml.sln /p:configuration=${{ inputs.configuration }} /p:platform=${{ inputs.platform }}

    - name: Upload build output
      uses: actions/upload-artifact@v4
      with:
        name: RNX ${{ inputs.configuration }} ${{ inputs.platform }} Build Output
        path: package\windows\${{ inputs.platform }}\${{ inputs.configuration }}\ReactNativeXaml\*.*
        if-no-files-found: error
